[package]
name = "fh-kiel-master-thesis"
entrypoint = "lib.typ"
description = "Unofficial template for writing a master-thesis in the FH Kiel department of Computer Science design."
categories = ["thesis"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
