[package]
name = "fh-kiel-report"
entrypoint = "lib.typ"
description = "Unofficial template for writing a report in the FH Kiel department of Computer Science design."
categories = ["report"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
